name: PlayingBig
favicon: null
layout_spectrum: 0.38774
typography_spectrum: 0.53138
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6a6a6a'
    - '#fdab71'
    - '#b18c79'
    - '#43322b'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
