name: PlayingBig
favicon: null
layout_spectrum: 0.04154
typography_spectrum: 0.53138
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7facf'
    - '#4d5049'
    - '#342834'
    - '#699983'
    - '#bfdbab'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
